name: Publish Release

permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths:
      - 'Flow.Launcher.Plugin.ShortcutPlugin/plugin.json'
  workflow_dispatch:

jobs:
  publish:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Flow.Launcher.Plugin.ShortcutPlugin/plugin.json'
          prop_path: 'Version'

      - run: echo ${{steps.version.outputs.prop}}

      - name: Restore dependencies
        run: |
          cd Flow.Launcher.Plugin.ShortcutPlugin
          dotnet restore

      - name: Build
        run: |
          cd Flow.Launcher.Plugin.ShortcutPlugin
          dotnet publish -c Release -r win-x64 --no-self-contained Flow.Launcher.Plugin.ShortcutPlugin.csproj
          7z a -tzip "Flow.Launcher.Plugin.ShortcutPlugin.zip" "./bin/Release/win-x64/publish/*"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Flow.Launcher.Plugin.ShortcutPlugin/Flow.Launcher.Plugin.ShortcutPlugin.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
